### ISSUE TITLE
Edits do not trigger EditorJS’s onChange()

### ISSUE THREAD

**Issue by hagemann** [editor-js/raw#12] opened 2020-04-01 20:41 UTC
After page load, initial edits in the textarea do not trigger the EditorJS `onChange` listener unless other blocks are modified first.

**Comment by Darkinsideus** [comment] 2020-04-04 16:56
Confirm. Until you make changes in other blocks, it doesn't save changes in raw block.

**Comment by VitaliyDemchuk** [comment] 2020-04-17 21:13
This is a critical bug. When will the fix be?

**Comment by m-alzam** [comment] 2020-04-18 13:45
> After page load, initial edits in the textarea do not trigger the EditorJS `onChange` listener unless other blocks are modified first.

I can't reproduce this issue - works for me.

**Comment by hagemann** [comment] 2020-04-18 15:48
@m-alzam Without touching anything and typing in the textbox the first thing?

**Comment by m-alzam** [comment] 2020-04-18 16:04
> @m-alzam Without touching anything and typing in the textbox the first thing?

Hmm, confirmed. The `onChange` listener is not triggered. It maybe related to #843

**Comment by neSpecc** [comment] 2020-11-10 12:55
Should be fixed in editorjs 2.19

**Closed by neSpecc** 2020-11-10 12:55 UTC
